### ISSUE TITLE
Question: how to get the correct encoding?

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/NPCSManager#2]
i try on a game that use the same engine, but as you can see, it turn the text into garbage,
i know, i need to manually map the character on encoding.cs,
but how exactly i can get the correct character map?
first of all, its not a pc game, but the vita one.
![untitled22](https://user-images.githubusercontent.com/23132217/53321872-41edb900-390c-11e9-9d00-90dfcd27d091.PNG)

**Comment by marcussacana** [comment]
Basically, Run the game, found the same dialog in the game and in the script, See the hex code of all characters and put in the encoding.cs

As you can see, is a insane work (if is a japanese script), and no, don't have a automatically way to do this, If there were an easier way, my tool would already use it.

To help found the text in the script, you can use this tool: https://github.com/marcussacana/EXSearch

**Comment by 0xh3LL0** [comment]
thanks, may as well i try to do this...
