### ISSUE TITLE
Text crash problem

### ISSUE THREAD

**Issue by Tfausx** [marcussacana/NPCSManager#3]
Hi Marcus, i hope you're having a nice day! I come here with a question related with a game of N+, more specifically, Muramasa (i know this is more related to Nitro - Mages games new engine) but maybe you can help me with the problem!

The problem it's:

Today i was testing my translation of this game, but on certain scripts, the game crash showing this "format text"

Normal:
![imagen](https://user-images.githubusercontent.com/29191836/113518766-b15c1b00-955e-11eb-94c4-8f085b1552d4.png)

Weird text before crash the game:

![imagen](https://user-images.githubusercontent.com/29191836/113518782-c8027200-955e-11eb-8a18-8b0d74846ef9.png)

Do you have any idea why this happen? The engine it's the old N+ (.nss format) If you want to check for yourself, i can sent you the script to your mail!

Thanks in advance!

**Comment by marcussacana** [comment]
This is a very old tool that I made, I remeber nothing about this format to say, but this should be a problem with my tool probabbly.

**Comment by Tfausx** [comment]
Don't worry, i have solved it! Thanks !
